// Generated by https://quicktype.io

export interface PokemonListResponse {
  count:    number;
  next?:     string; //? esto significa que son opcionales
  previous?: string;
  results:  SmallPokemon[]; // esto es un array de objetos
}

export interface SmallPokemon {
  name: string;
  url:  string;
  id:  number;
  img:  string;
}
